// Misa's animation sheets, generated by Moonkai Pixel Studio's Character builder
// (tools/moonkai-export.mjs -> assets/moonkai/*.png). The builder draws a right-facing profile.
const SHEETS = {
  misa_sheet: { size: 64, idle: 8, walk: 12, run: 10, row: { idle: 0, walk: 1, run: 2 } },
  misa_big: { size: 128, idle: 8, walk: 12, row: { idle: 0, walk: 1 } },
};
const imgs = {};

export function loadMisa() {
  return Promise.all(Object.keys(SHEETS).map((k) => new Promise((res) => {
    const img = new Image();
    img.onload = () => { imgs[k] = img; res(); };
    img.onerror = () => res();
    img.src = (typeof window !== 'undefined' && window.MOONKAI_SHEETS && window.MOONKAI_SHEETS[k]) || `assets/moonkai/${k}.png`;
  })));
}
export const frameCount = (sheet, anim) => SHEETS[sheet][anim];

// Draw a frame with the feet centred on (x, y). flip = face left.
export function drawMisa(g, sheet, anim, frame, x, y, flip = false) {
  const S = SHEETS[sheet], img = imgs[sheet], n = S.size;
  if (!img) { g.fillStyle = '#3d5a8c'; g.fillRect(Math.round(x - n / 6), Math.round(y - n * 0.7), n / 3, n * 0.7); return; }
  const f = Math.floor(frame) % S[anim];
  g.save();
  g.translate(Math.round(x), 0);
  if (flip) g.scale(-1, 1);
  g.drawImage(img, f * n, S.row[anim] * n, n, n, -n / 2, Math.round(y - n * 0.95), n, n);
  g.restore();
}
