// Scattered writings: the history of Ashgate, the Binder Dukes, the bell and the sleepers.
// Each is a note the player can find in the wilds; reading one gives a little experience.
export const LORE = [
  { id: 'l_board', at: [6.5, 1.0, 17.5], prompt: 'Read the notice board', title: 'WANTED', text: 'WANTED, FOR THEFT OF A GOAT AND OTHER OFFENCES\n\nA hooded man seen on the King\'s Road. Height, middling. Manner, furtive. Reward: 40 gold for information.\n\n(Beneath, in another hand) It was not a goat. It was a sheep. Get it right.' },
  { id: 'l_road', at: [2.2, 0.9, -91], prompt: 'Read the waystone', title: 'THE FOUR LIGHTS', text: 'Four stones, cut before the Dukes, before the road. Each was set where the ground is thin.\n\nTouch one and it takes your name. Touch four and the road remembers you, wherever it leads.\n\nDo not ask what the stones are keeping out.' },
  { id: 'l_bridge', at: [6.5, 1.0, -213], prompt: 'Read the toll ledger', title: 'TOLL LEDGER, GREYWATER', text: 'Wagons: 41. Heads: 212. Pilgrims: 9 (turned back). Carters refusing: 3.\n\nThe river ran red on the 4th, but only in the morning. Bosk says it is iron in the hills. Bosk has said the same about the singing.\n\nNote: nobody has crossed north-to-south in eleven days.' },
  { id: 'l_farm', at: [28.4, 1.0, -142.2], prompt: 'Read the scrap', title: 'A FARMER\'S SCRAP', text: 'Second harvest gone thin. The turnips come up pale, and the crows will not settle on the barn.\n\nMaren says the well tastes of coins. I drank it anyway. Nothing happened. That worries me more.' },
  { id: 'l_lodge', at: [-126.4, 1.0, -73.5], prompt: 'Read the carved plank', title: 'CARVED ON A PLANK', text: 'W. Hunts. Deer 2, hares 5. Bandit 1 (regretted).\n\nThe wolves left in spring. Not hunted out. Left. Wolves do not leave a place for no reason. They leave it when something else has moved in.' },
  { id: 'l_bandit', at: [-166.5, 1.0, 8.5], prompt: 'Read the crumpled letter', title: 'A CRUMPLED LETTER', text: 'Cael. The Duke\'s steward pays double for anyone who will keep the wood road shut. Do not ask why he wants the wood road shut.\n\nBurn this.\n\n(It was not burned.)' },
  { id: 'l_tower', at: [-116, 1.0, 63.2], prompt: 'Read the inscription', title: 'THE WATCH TOWER', text: 'This tower was raised by the second Vorst to watch the Mirewood for what came out of it.\n\nIt was abandoned when the watch began to watch each other instead.' },
  { id: 'l_witch', at: [-203.2, 0.8, 80.8], prompt: 'Read the nailed sign', title: 'NAILED TO A POST', text: 'GO AWAY.\n\nIf you are a pilgrim: go away politely.\nIf you are a hunter: go away quickly.\nIf you are from the Hand: come in, and wipe your feet, and sit, and be told what you were born to be told.' },
  { id: 'l_fen', at: [-108, 0.6, -166.6], prompt: 'Read the marker', title: 'BOG MARKER', text: 'HERE A MAN LEFT THE BOARDS TO FOLLOW A LIGHT.\n\nHIS FRIENDS SAY THE LIGHT WAS KIND.\nTHE FEN SAYS OTHERWISE.\n\nKeep to the planks. The planks are mine. I laid them.' },
  { id: 'l_shrine', at: [-190, 0.7, -224.6], prompt: 'Read the drowned stone', title: 'THE DROWNED SAINT', text: 'THE PALE SAINT WEPT INTO THIS POOL FOR NINE YEARS,\nAND THE POOL WEPT BACK.\n\nWHAT SHE MOURNED WAS NOT A PERSON. IT WAS A DOOR.\nSHE COULD NOT CLOSE IT. SHE CAN ONLY WATCH IT.' },
  { id: 'l_cinder1', at: [150.6, 1.0, 55.6], prompt: 'Read the burnt sign', title: 'CINDERWICK, THREE YEARS AGO', text: 'The bell in the chapel tolled thirteen on the eve of harvest.\n\nBy morning half the village stood in the road facing the hill, silent, with their eyes open.\nBy the following night, the other half had learned to be afraid of them.' },
  { id: 'l_cinder2', at: [128.5, 1.0, 100.4], prompt: 'Read the singed page', title: 'A SINGED PAGE', text: '...it does not rise all at once. It rises the way a tide comes in: a little, and then a little, and you tell yourself you are standing on dry ground.\n\nThe Duke knows. The Duke wrote the letter that keeps the door. The Duke is very afraid of the day the wax cracks.' },
  { id: 'l_plague', at: [195.5, 1.0, 98.4], prompt: 'Read the gate tablet', title: 'THE PLAGUE WARD', text: 'HERE THE DEAD OF CINDERWICK WERE LAID, AND THE GATE LOCKED.\n\nTHE GATE HAS BEEN OPENED FROM THE INSIDE THREE TIMES SINCE.' },
  { id: 'l_gallows', at: [198, 1.0, 147.2], prompt: 'Read the notch-post', title: 'THE HANGMAN\'S TALLY', text: 'Thieves: 34. Deserters: 12. Heretics: 5. Duke\'s cousin: 1.\n\nThe last was the only one that did not struggle. He smiled at the rope. He told me the door was closing, and that I would be glad of it.' },
  { id: 'l_hermit', at: [-68.4, 0.9, -94], prompt: 'Read the etched stone', title: 'OSWIN\'S NOTE', text: 'I was a scholar once. I read the wrong book. I stayed here to keep the fire lit for the ones who carry the letter, because someone should be kind to them.\n\nEvery carrier has been a thief. Every thief has thought it was their idea.' },
  { id: 'l_bell', at: [-27.4, 1.0, 74.4], prompt: 'Read the bell-ringer\'s log', title: 'THE BELL LOG', text: 'Twelve. Twelve. Twelve. Thirteen.\n\nI did not pull the rope. I want that written. I did not pull the rope, and the bell tolled thirteen, and the ground under the chapel answered.' },
];
